import addressPickerPage from '../../support/page-object/address_picker.page.js'
/// <reference types="Cypress" />
describe("C5. Two-line format,  pre-filled (#twoLinePreFilled0) block testing", () => {
    beforeEach(() => {
      cy.visit('/');
    });
    it('1. Check block title to be visible and have valid text', () => {
        addressPickerPage.headerTitleVerifyTwoLinePreFilledZero('Two-line format,  pre-filled')
    })
    xit('2. Check "View code" button to be visible, not disabled. Check that clicking on button shows code in tabs and hide code after one more click on it. (pending while in local)', () => {
        addressPickerPage.headerButtonVerifyTwoLinePreFilledZero(0, 'mat-focus-indicator mat-tooltip-trigger mat-icon-button mat-button-base')
    })
    it('3. Check input title to be visible, have valid class and text. Check input field to be pre-filled. Clear button to be visible and not disabled. Click on it. Check input field to be clear.', () => {
        addressPickerPage.inputTitleVerifyTwoLinePreFilledZero('ng-tns-c145-2 ng-star-inserted', 'Location')
        addressPickerPage.selectedAddrVerifyTwoLinePreFilledZero(1, 12, 'Selected Address', ['CN Tower','301 Front Street West','Toronto','ON','M5V 2T6','CA','CN Tower','301 Front Street West','Toronto','ON','M5V 2T6','CA'])
        addressPickerPage.addressPreviewClearButtonVerifyTwoLinePreFilledZero(0, 'mat-icon notranslate control material-icons mat-icon-no-color ng-tns-c145-2 ng-star-inserted')
        addressPickerPage.addressPreviewClearButtonVerifyTwoLinePreFilledZero(1)
        cy.wait(500)
        addressPickerPage.selectedAddrVerifyTwoLinePreFilledZero(0)
        addressPickerPage.inputFieldVerifyTwoLinePreFilledZero(0, 'mat-form-field-autofill-control mat-autocomplete-trigger ng-untouched ng-pristine ng-valid cdk-text-field-autofill-monitored')
    })
    it('4. Testing autocomplete function. Clear input field. Fill input and select item from dropdown options. Click on input field to open manual input window. Check titles to have valid text, inputs to contain autocomplete value or be empty. Type new text. Check footer buttons to be visible, not disabled, have valid class and text. Check buttons to work correctly', () => {
        addressPickerPage.addressPreviewClearButtonVerifyTwoLinePreFilledZero(1)
        addressPickerPage.inputFieldVerifyTwoLinePreFilledZero(1, '240 McLeod St')
        addressPickerPage.selectAutocompleteVariantTwoLinePreFilledZero('240 McLeod St')
        addressPickerPage.addressPreviewTwoLinePreFilledZero.eq(0).click()
        addressPickerPage.manualAddrWindowInputAndTitleOneAddressPickerPage(0, 'Location name', 0, 'This is test')
        addressPickerPage.manualAddrWindowInputAndTitleOneAddressPickerPage(1, 'Street', '240 McLeod Street', 'This is test')
        addressPickerPage.manualAddrWindowInputAndTitleOneAddressPickerPage(2, 'City', 'Ottawa', 'This is test')
        addressPickerPage.manualAddrWindowInputAndTitleOneAddressPickerPage(3, 'Province', '[object Object]', 'Ontario')
        addressPickerPage.manualAddrWindowInputAndTitleOneAddressPickerPage(5, 'Postal Code', 'K2P 2R1', 'This is test')
        addressPickerPage.manualAddrWindowInputAndTitleOneAddressPickerPage(4, 'Country', '[object Object]', 'Canada')
        addressPickerPage.manualAddrWindowInputAndTitleOneAddressPickerPage(3, 'Province', 0, 'Ontario')
        addressPickerPage.footerButtonVerifyAddrAddressPickerPage(0,1, 'mat-focus-indicator mat-button mat-button-base mat-primary', 'Apply')
        addressPickerPage.footerButtonVerifyAddrAddressPickerPage(1,1, 'mat-focus-indicator mat-button mat-button-base', 'Cancel')
        addressPickerPage.footerButtonVerifyAddrAddressPickerPage(2,0)
        addressPickerPage.footerButtonsAddressPickerPage.contains('Apply').click()
        addressPickerPage.selectedAddrVerifyTwoLinePreFilledZero(1, 12, 'Selected Address', ['This is test','This is test','This is test','ON','This is test','CA','This is test','This is test','This is test','ON','This is test','CA'])
        cy.reload()

        addressPickerPage.addressPreviewClearButtonVerifyTwoLinePreFilledZero(1)
        addressPickerPage.inputFieldVerifyTwoLinePreFilledZero(1, '240 McLeod St')
        addressPickerPage.selectAutocompleteVariantTwoLinePreFilledZero('240 McLeod St')
        addressPickerPage.addressPreviewTwoLinePreFilledZero.eq(0).click()
        addressPickerPage.manualAddrWindowInputAndTitleOneAddressPickerPage(0, 'Location name', 0, '240 McLeod Street')
        addressPickerPage.manualAddrWindowInputAndTitleOneAddressPickerPage(1, 'Street', '240 McLeod Street', '240 McLeod Street')
        addressPickerPage.manualAddrWindowInputAndTitleOneAddressPickerPage(2, 'City', 'Ottawa', 'Ottawa')
        addressPickerPage.manualAddrWindowInputAndTitleOneAddressPickerPage(3, 'Province', '[object Object]', 'Ontario')
        addressPickerPage.manualAddrWindowInputAndTitleOneAddressPickerPage(5, 'Postal Code', 'K2P 2R1', 'K2P 2R1')
        addressPickerPage.manualAddrWindowInputAndTitleOneAddressPickerPage(4, 'Country', '[object Object]', 'Canada')
        addressPickerPage.manualAddrWindowInputAndTitleOneAddressPickerPage(3, 'Province', 0, 'Ontario')
        addressPickerPage.footerButtonVerifyAddrAddressPickerPage(0,1, 'mat-focus-indicator mat-button mat-button-base mat-primary', 'Apply')
        addressPickerPage.footerButtonVerifyAddrAddressPickerPage(1,1, 'mat-focus-indicator mat-button mat-button-base', 'Cancel')
        addressPickerPage.footerButtonVerifyAddrAddressPickerPage(2,0)
        addressPickerPage.footerButtonsAddressPickerPage.contains('Cancel').click()
        addressPickerPage.selectedAddrVerifyTwoLinePreFilledZero(1, 10, 'Selected Address', ['240 McLeod Street','Ottawa','ON','K2P 2R1','CA','240 McLeod Street','Ottawa','ON','K2P 2R1','CA'])
    })
    it('5. Check manual address input. Clear input field. Select item "Enter address manually" from dropdown options. Check titles to have valid text, inputs to be empty. Type text. Click on "Apply" button and check selected address panel to contain valid text', () => {
        addressPickerPage.addressPreviewClearButtonVerifyTwoLinePreFilledZero(1)
        addressPickerPage.inputFieldVerifyTwoLinePreFilledZero(1, ' ')
        addressPickerPage.selectAutocompleteVariantTwoLinePreFilledZero(' Enter address manually ')
        addressPickerPage.manualAddrWindowInputAndTitleOneAddressPickerPage(0, 'Location name', 0, '240 McLeod Street')
        addressPickerPage.manualAddrWindowInputAndTitleOneAddressPickerPage(1, 'Street', 0, '240 McLeod Street')
        addressPickerPage.manualAddrWindowInputAndTitleOneAddressPickerPage(2, 'City', 0, 'Ottawa')
        addressPickerPage.manualAddrWindowInputAndTitleOneAddressPickerPage(3, 'Province', 0, 'Ontario')
        addressPickerPage.manualAddrWindowInputAndTitleOneAddressPickerPage(5, 'ZIP/Postal Code', 0, 'K2P 2R1')
        addressPickerPage.manualAddrWindowInputAndTitleOneAddressPickerPage(4, 'Country', 0, 'Canada')
        addressPickerPage.manualAddrWindowInputAndTitleOneAddressPickerPage(3, 'Province', 0, 'Ontario')
        addressPickerPage.footerButtonsAddressPickerPage.contains('Apply').click()
        addressPickerPage.selectedAddrVerifyTwoLinePreFilledZero(1, 12, 'Selected Address', ['240 McLeod Street','240 McLeod Street','Ottawa','ON','K2P 2R1','CA','240 McLeod Street','240 McLeod Street','Ottawa','ON','K2P 2R1','CA'])
    })
})